Repository 2025SWDesign/Frontend, pull requests merged in 2025-04, with the labels that each got.

#8 design: 학생 정보 클릭 시 sidebar에 이미지 및 학생 정보 표시, 테이블 필터링
  public/assets/img/Logo.png
  public/assets/img/Logo_2.png
  public/assets/img/photo.png
  public/assets/img/searchButton.png
  public/vite.svg
  src/assets/react.svg
  src/layouts/MainLayout.styled.ts
  src/layouts/MainLayout.tsx
  src/page/CounselingPage.styled.ts
Labels: 🎨 design

#15 design: 초기페이지 드롭다운 메뉴(유저, 알림) 구현
  src/index.css
  src/layouts/MainLayout.styled.ts
  src/layouts/MainLayout.tsx
Labels: 🎨 design

#17 design: 로그인/회원가입 페이지 구현
  public/assets/img/Logo_2w.png
  src/App.tsx
  src/page/SignInPage.styled.ts
  src/page/SignInPage.tsx
Labels: 🎨 design

#19 design: 탭 버튼 색변경 방식 변경 및 학생 선택 시 StudentInfo로 이동하도록 수정
  src/App.tsx
  src/layouts/MainLayout.styled.ts
  src/layouts/MainLayout.tsx
  src/page/StudentInfoPage.tsx
Labels: 🎨 design

#20 Design/#15
  src/App.tsx
  src/page/CounselingWritePage.styled.ts
  src/page/CounselingWritePage.tsx
  src/page/StudentManagementPage.styled.ts
  src/page/StudentManagementPage.tsx
Labels: 🎨 design

#22 feat:학생/학부모 퍼블리싱(1) 완료
  src/App.tsx
  src/layouts/MainLayout.tsx
  src/page/CounselingPage.tsx
  src/page/FeedbackPage.styled.ts
  src/page/FeedbackPage.tsx
  src/page/StudentManagementPage.styled.ts
  src/page/StudentManagementPage.tsx
Labels: 🎨 design, 🐛 fix

#24 feat: 피드백 페이지 학년 추가
  src/page/FeedbackPage.styled.ts
  src/page/FeedbackPage.tsx
Labels: 🎨 design

#26 design: 초기화면 레이아웃(담임 ver) 퍼블리싱 및 identity 관리 변경
  src/App.tsx
  src/layouts/MainLayout.styled.ts
  src/layouts/MainLayout.tsx
  src/page/MainPage.tsx
Labels: ✨ feat

#29 design: 학생 성적 관리 페이지 퍼블리싱
  package.json
  src/App.tsx
  src/Components/RadarChart.tsx
  src/layouts/MainLayout.styled.ts
  src/layouts/MainLayout.tsx
  src/page/FeedbackPage.styled.ts
  src/page/GradePage.styled.ts
  src/page/GradePage.tsx
  yarn.lock
Labels: 🎨 design

#31 design: 학생 성적 관리 페이지 퍼블리싱(담임 ver)
  src/App.tsx
  src/layouts/MainLayout.tsx
  src/page/GradePage.styled.ts
  src/page/GradePage.tsx
Labels: 🎨 design

#33 Design/#28
  src/App.tsx
  src/layouts/MainLayout.tsx
  src/page/CounselingPage.styled.ts
  src/page/CounselingPage.tsx
  src/page/FeedbackPage.styled.ts
  src/page/FeedbackPage.tsx
Labels: 🎨 design

#37 design: 보고서생성 페이지 구현
  src/App.tsx
  src/Components/CounselingReport.styled.ts
  src/Components/CounselingReport.tsx
  src/Components/FeedbackReport.styled.ts
  src/Components/FeedbackReport.tsx
  src/Components/ScoreReport.styled.ts
  src/Components/ScoreReport.tsx
  src/layouts/MainLayout.tsx
  src/page/ReportPage.styled.ts
  src/page/ReportPage.tsx
Labels: 🎨 design

#38 Design/#36
  src/App.tsx
  src/page/CounselingPage.tsx
  src/page/CounselingWritePage.styled.ts
  src/page/CounselingWritePage.tsx
  src/page/SignInPage.styled.ts
  src/page/SignInPage.tsx
  src/page/StudentInfoPage.styled.ts
  src/page/StudentInfoPage.tsx
Labels: 🎨 design

#40 design: 마이페이지 퍼블리싱 및 담임교사 관리
  src/App.tsx
  src/Components/FeedbackReport.tsx
  src/layouts/MainLayout.tsx
  src/page/MyPage.styled.tsx
  src/page/MyPage.tsx
Labels: 🎨 design

#42 design: MainLayout 변경한 디자인 반영
  src/layouts/MainLayout.styled.ts
  src/layouts/MainLayout.tsx
  src/page/CounselingPage.styled.ts
  src/page/CounselingPage.tsx
  src/page/GradePage.styled.ts
  src/page/ReportPage.styled.ts
  src/page/ReportPage.tsx
Labels: 🎨 design

#44 design: 담임교사용 성적관리페이지 변경
  src/layouts/MainLayout.styled.ts
  src/page/GradePage.styled.ts
  src/page/GradePage.tsx
Labels: 🎨 design

#49 feat: 회원가입 API 연동(이메일)
  package.json
  src/page/SignInPage.styled.ts
  src/page/SignInPage.tsx
  vite.config.ts
  yarn.lock
Labels: ✨ feat

#51 design: 카카오 로그인/회원가입 용 퍼블리싱
  src/page/SignInPage.styled.ts
  src/page/SignInPage.tsx
Labels: 🎨 design

#52 학생 검색 API 연동(1) 완료
  package.json
  src/App.tsx
  src/layouts/MainLayout.tsx
  src/page/CounselingPage.tsx
  src/page/FeedbackPage.tsx
  src/page/GradePage.tsx
  src/page/ReportPage.tsx
  src/page/StudentInfoPage.tsx
  src/page/StudentManagementPage.tsx
  {
Labels: ✨ feat

#54 feat: 로그인 API 연동 및 내 정보 조회 API 연동
  src/App.tsx
  src/context/AuthContext.tsx
  src/context/AuthProvider.tsx
  src/hooks/useAuth.ts
  src/layouts/MainLayout.tsx
  src/page/GradePage.tsx
  src/page/MyPage.tsx
  src/page/ReportPage.tsx
  src/page/SignInPage.styled.ts
  src/page/SignInPage.tsx
Labels: ✨ feat

#57 feat: MainLayout 로그아웃 API 연동
  src/layouts/MainLayout.tsx
Labels: ✨ feat

#59 학생 관리 API 연동(2) 완료
  src/layouts/MainLayout.tsx
  src/page/SignInPage.tsx
  src/page/StudentManagementPage.tsx
Labels: ✨ feat

#63 feat: 기존 ContextAPI로 하던 전역상태 관리 라이브러리를 Zustand로 변경
  package.json
  src/App.tsx
  src/Components/CounselingReport.tsx
  src/Components/FeedbackReport.tsx
  src/Components/ScoreReport.tsx
  src/context/AuthContext.tsx
  src/context/AuthProvider.tsx
  src/hooks/useAuth.ts
  src/layouts/MainLayout.tsx
  src/page/CounselingPage.tsx
  src/page/FeedbackPage.tsx
  src/page/GradePage.tsx
  src/page/MainPage.tsx
  src/page/MyPage.tsx
  src/page/ReportPage.tsx
  src/page/SignInPage.tsx
  src/page/StudentInfoPage.tsx
  src/page/StudentManagementPage.styled.ts
  src/page/StudentManagementPage.tsx
  src/stores/authStore.ts
  src/stores/studentStore.ts
  yarn.lock
  {
Labels: ✨ feat

#65 feat: 토큰 재발급 API 연동 및 axiosInstance 구현
  src/api/axiosInstance.ts
  src/layouts/MainLayout.tsx
Labels: ✨ feat

#67 피드백 내역 API 연동 완료
  src/layouts/MainLayout.tsx
  src/page/CounselingWritePage.styled.ts
  src/page/CounselingWritePage.tsx
  src/page/FeedbackPage.styled.ts
  src/page/FeedbackPage.tsx
  src/page/StudentManagementPage.tsx
Labels: ✨ feat

#71 feat: Kakao 소셜로그인 API 연동
  src/page/SignInPage.tsx
Labels: ✨ feat

#72 상담 내역 API 연동 완료
  src/page/CounselingPage.styled.ts
  src/page/CounselingPage.tsx
  src/page/CounselingWritePage.tsx
Labels: ✨ feat

#74 상담 내역 날짜로 검색하기 버그 수정 완료
  src/page/CounselingPage.tsx
Labels: 🐛 fix

#78 feat: 보고서 생성(PDF/Excel) 기능 구현
  package.json
  src/page/ReportPage.styled.ts
  src/page/ReportPage.tsx
  yarn.lock
Labels: ✨ feat

#79 feat: GradePage 반 학생의 전체 성적 조회 API 연동
  src/layouts/MainLayout.tsx
  src/page/GradePage.tsx
  src/stores/authStore.ts
Labels: ✨ feat

#82 feat: 특정 학생의 성적 입력 및 수정 API 연동
  src/page/GradePage.tsx
Labels: ✨ feat

#83 학생부 관리 API 연동 완료
  src/layouts/MainLayout.tsx
  src/page/StudentManagementPage.styled.ts
  src/page/StudentManagementPage.tsx
  src/stores/authStore.ts
Labels: ✨ feat

#84 feat: 특정 학생 성적 조회(과목별/기간별) API 연동
  src/Components/RadarChart.tsx
  src/page/GradePage.tsx
Labels: ✨ feat

#87 필터링 추가 완료
  src/layouts/MainLayout.tsx
  src/page/CounselingPage.tsx
  src/stores/authStore.ts
Labels: ✨ feat

#89 오류 수정
  src/page/FeedbackPage.tsx
Labels: 🐛 fix

#91 수정 완료
  src/page/CounselingPage.tsx
Labels: 🔨 refactor

#93 제발 되라
  src/page/GradePage.tsx
  src/page/ReportPage.tsx
  src/temp/CounselingReport.styled.ts
  src/temp/CounselingReport.tsx
  src/temp/FeedbackReport.styled.ts
  src/temp/FeedbackReport.tsx
  src/temp/RadarChart.tsx
  src/temp/ScoreReport.styled.ts
  src/temp/ScoreReport.tsx
Labels: 🔨 refactor

#95 제발
  src/components/CounselingReport.styled.ts
  src/components/CounselingReport.tsx
  src/components/FeedbackReport.styled.ts
  src/components/FeedbackReport.tsx
  src/components/RadarChart.tsx
  src/components/ScoreReport.styled.ts
  src/components/ScoreReport.tsx
  src/page/GradePage.tsx
  src/page/ReportPage.tsx
Labels: 🔨 refactor

#97 proxy 주소 변경
  vite.config.ts
Labels: ✨ feat

#99 vercel.json 추가
  vercel.json
Labels: ✨ feat

#100 feat: 성적보고서 생성을 위한 특정 학생의 특정 기간 성적 조회 API 연동
  src/page/ReportPage.tsx
Labels: ✨ feat

#102 fix: 피드백 props 제거
  src/page/FeedbackPage.tsx
Labels: 🐛 fix
