Repository 2025SWDesign/Frontend, pull requests merged in 2025-05, with the labels that each got.

#105 버셀 우회용 파일 추가 완료
  .github/workflows/deploy.yml
  build.sh
Labels: ✨ feat

#107 수정 완료
  .github/workflows/deploy.yml
Labels: 🐛 fix

#108 feat: 피드백보고서 생성을 위한 특정 학생 피드백 전체 조회 API 연동
  src/components/FeedbackReport.tsx
  src/page/ReportPage.tsx
Labels: ✨ feat

#113 테스트 코드 추가
  .github/workflows/playwright.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  src/page/SignInPage.tsx
  tests-examples/demo-todo-app.spec.ts
  tests/SignInPage.spec.ts
  tsconfig.node.json
  yarn.lock
Labels: ✨ feat

#114 Feat/#112
  src/layouts/MainLayout.tsx
  src/page/SignInPage.tsx
  tests/MainLayout.spec.ts
  tests/SignInPage.spec.ts
Labels: ✨ feat

#116 mainLayout testId 추가
  src/layouts/MainLayout.tsx
  tests/MainLayout.spec.ts
Labels: ✨ feat

#119 feat: 알림 내역 전체 조회 API 연동
  public/assets/img/bell-alert.png
  src/layouts/MainLayout.styled.ts
  src/layouts/MainLayout.tsx
Labels: ✨ feat

#121 Feat/#117
  src/page/CounselingWritePage.tsx
  tests/CounselingPage.spec.ts
  tests/CounselingWritePage.spec.ts
  tests/FeedbackPage.spec.ts
  tests/GradePage.spec.ts
  tests/MainLayout.spec.ts
  tests/MyPage.spec.ts
  tests/ReportPage.spec.ts
  tests/SignInPage.spec.ts
  tests/StudentInfoPage.spec.ts
  tests/StudentManagementPage.spec.ts
Labels: ✨ feat

#123 testId추가
  src/page/StudentManagementPage.tsx
  tests/MainLayout.spec.ts
  tests/StudentInfoPage.spec.ts
  tests/StudentManagementPage.spec.ts
Labels: ✨ feat

#122 feat: 알림 내역 상세 조회 API 연동
  src/layouts/MainLayout.styled.ts
  src/layouts/MainLayout.tsx
Labels: ✨ feat

#126 feat: MyPage 비밀번호 변경 API 연동
  src/page/MyPage.styled.tsx
  src/page/MyPage.tsx
  vite.config.ts
Labels: ✨ feat

#128 design: 마이페이지 user role에 따라 UI 수정
  src/page/MyPage.styled.tsx
  src/page/MyPage.tsx
  vite.config.ts
Labels: 🎨 design

#132 상담 내역 test 완료
  src/page/CounselingPage.tsx
  src/page/CounselingWritePage.tsx
  tests/CounselingPage.spec.ts
  tests/StudentManagementPage.spec.ts
Labels: ✨ feat

#134 feat: MyPage 개인정보수정 API 연동
  src/page/MyPage.styled.tsx
  src/page/MyPage.tsx
Labels: ✨ feat

#136 feat: MyPage에서 담임권한설정 API 연동
  src/page/MyPage.tsx
  src/stores/authStore.ts
Labels: ✨ feat

#140 fix: 반 학생 성적 목록에 성적이 기입되지않았더라도 출력되도록 수정
  src/layouts/MainLayout.tsx
  src/page/GradePage.tsx
Labels: 🐛 fix

#142 fix: 학생 계정으로 로그인 시 MyPage 접근이 불가능한 오류 수정
  src/page/MyPage.tsx
Labels: 🐛 fix

#143 학생 성적 페 이지 test 추가
  package-lock.json
  package.json
  src/page/GradePage.tsx
  tests/GradePage.spec.ts
  yarn.lock
Labels: ✨ feat

#147 보고서 페이지 test 추가 및 일부 수정
  src/layouts/MainLayout.tsx
  src/page/FeedbackPage.styled.ts
  src/page/FeedbackPage.tsx
  src/page/ReportPage.tsx
  src/page/StudentInfoPage.tsx
  src/page/StudentManagementPage.styled.ts
  src/page/StudentManagementPage.tsx
  tests/ReportPage.spec.ts
  tests/StudentInfoPage.spec.ts
  tests/StudentManagementPage.spec.ts
Labels: ✨ feat, 🐛 fix

#148 보고서 페이지 test 추가
  src/page/ReportPage.tsx
  tests/ReportPage.spec.ts
Labels: ✨ feat

#151 관리자 페이지 퍼블리싱 완
  src/App.tsx
  src/layouts/MainLayout.styled.ts
  src/layouts/MainLayout.tsx
  src/page/AdminPage.styled.ts
  src/page/AdminPage.tsx
  src/page/MainPage.tsx
Labels: 🎨 design

#153 수정 완
  src/page/AdminPage.tsx
Labels: 🐛 fix

#155 mainLayout 수정 완
  src/layouts/MainLayout.tsx
Labels: 🐛 fix

#159 design: MyPage 학부모 계정 생성 버튼 추가
  src/page/MyPage.styled.tsx
  src/page/MyPage.tsx
Labels: 🎨 design

#161 design: 회원가입 변경에 따른 로그인 페이지 UI 변경
  src/page/MyPage.styled.tsx
  src/page/SignInPage.tsx
Labels: 🎨 design

#162 어드민 페이지 수정
  src/App.tsx
  src/layouts/MainLayout.tsx
  src/page/AdminAddPage.styled.ts
  src/page/AdminAddPage.tsx
  src/page/AdminAssignPage.styled.ts
  src/page/AdminAssignPage.tsx
  src/page/AdminPage.styled.ts
  src/page/AdminPage.tsx
  src/page/MainPage.tsx
  src/stores/authStore.ts
Labels: ✨ feat

#164 테스트 코드 추가 완료
  src/layouts/MainLayout.tsx
  src/page/MyPage.tsx
  src/page/SignInPage.tsx
  tests/MyPage.spec.ts
  tests/SignInPage.spec.ts
  tests/StudentManagementPage.spec.ts
Labels: ✨ feat

#167 feat: 인증 코드 발송 API 연동
  src/page/SignInPage.tsx
Labels: ✨ feat

#169 어드민 페이지 이메일 추가
  src/page/AdminAddPage.tsx
Labels: ✨ feat

#171 feat: 인증 코드 확인 API 연동
  src/page/SignInPage.tsx
Labels: ✨ feat

#173 feat: 새 비밀번호 설정 API 연동
  src/page/SignInPage.tsx
Labels: ✨ feat

#175 Feat/#170
  src/page/AdminAddPage.tsx
  src/page/AdminAssignPage.tsx
  src/page/FeedbackPage.tsx
  src/page/MainPage.tsx
Labels: ✨ feat

#179 어드민 페이지 api 연동 완
  src/layouts/MainLayout.tsx
  src/page/AdminAssignPage.tsx
  tests/CounselingPage.spec.ts
  tests/FeedbackPage.spec.ts
  tests/GradePage.spec.ts
  tests/MainLayout.spec.ts
  tests/MyPage.spec.ts
  tests/ReportPage.spec.ts
  tests/SignInPage.spec.ts
  tests/StudentInfoPage.spec.ts
  tests/StudentManagementPage.spec.ts
Labels: ✨ feat

#182 design: 메인레이아웃(모바일) 퍼블리싱
  src/hooks/UseMobile.ts
  src/layouts/MainLayout.styled.ts
  src/layouts/MainLayout.tsx
  src/page/MainPage.tsx
  src/styles/media.ts
Labels: 🎨 design

#187 모바일 퍼블리싱(학생 정보 페이지)
  src/layouts/MainLayout.styled.ts
  src/page/StudentInfoPage.styled.ts
  src/page/StudentInfoPage.tsx
Labels: 🎨 design

#200 design: 보고서페이지(모바일) 퍼블리싱
  src/components/CounselingReport.styled.ts
  src/components/FeedbackReport.styled.ts
  src/components/ScoreReport.styled.ts
  src/page/ReportPage.styled.ts
  src/page/ReportPage.tsx
Labels: 🎨 design

#202 fix: 특정학생의 성적관리(과목별) 오류 수정
  src/page/GradePage.tsx
Labels: 🐛 fix

#208 학생, 일반 선생 테스트 코드 작성
  src/layouts/MainLayout.tsx
  src/page/CounselingPage.tsx
  src/page/FeedbackPage.tsx
  src/page/GradePage.tsx
  src/page/StudentInfoPage.tsx
  src/page/StudentManagementPage.tsx
  tests/CounselingPage.spec.ts
  tests/FeedbackPage.spec.ts
  tests/GradePage.spec.ts
  tests/MainLayout.spec.ts
  tests/MyPage.spec.ts
  tests/ReportPage.spec.ts
  tests/SignInPage.spec.ts
  tests/StudentInfoPage.spec.ts
  tests/StudentManagementPage.spec.ts
Labels: ✨ feat
