Repository 2025SWDesign/Frontend, pull requests merged in 2025-06, with the labels that each got.

#217 fix: 카카오 연동 수정
  src/page/MyPage.tsx
  vercel.json
Labels: 🐛 fix

#223 소나큐브 일부 수정
  src/layouts/MainLayout.tsx
  src/layouts/useSearch.ts
  src/page/MyPage.tsx
  src/page/ReportPage.tsx
Labels: 🐛 fix

#225 소나 큐브 수정
  playwright.config.ts
  src/api/axiosInstance.ts
  src/layouts/MainLayout.tsx
  src/page/MyPage.tsx
  src/page/ReportPage.tsx
  src/page/SignInPage.tsx
Labels: 🔨 refactor

#230 리펙토링
  src/page/SignInPage.styled.ts
  src/page/SignInPage.tsx
  src/page/StudentManagementPage.tsx
  tests-examples/demo-todo-app.spec.ts
  tests/AdminAssignPage.spec.ts
  tests/GradePage.spec.ts
  tests/SignInPage.spec.ts
Labels: 🔨 refactor

#233 중복 리펙토링
  src/page/GradePage.tsx
  tests/CounselingPage.spec.ts
  tests/MyPage.spec.ts
  tests/StudentInfoPage.spec.ts
Labels: 🔨 refactor

#235 refactor
  tests/FeedbackPage.spec.ts
  tests/GradePage.spec.ts
  tests/ReportPage.spec.ts
Labels: 🔨 refactor

#239 수정
  src/page/StudentManagementPage.styled.ts
  src/page/StudentManagementPage.tsx
  tests/StudentManagementPage.spec.ts
Labels: 🐛 fix

#241 비밀번호 찾기 UI 변경
  src/page/SignInPage.styled.ts
Labels: 🎨 design
